insert into actor (actor_name) values ('Dagmar Aldiss');
insert into actor (actor_name) values ('Hally Whitwell');
insert into actor (actor_name) values ('Christel MacGeaney');
insert into actor (actor_name) values ('Hyacinthie Zimmermanns');
insert into actor (actor_name) values ('Ban Owenson');
insert into actor (actor_name) values ('Vernice Whaplington');
insert into actor (actor_name) values ('Lemar Clampe');
insert into actor (actor_name) values ('Levon Pecey');
insert into actor (actor_name) values ('Sayer MacKinnon');
insert into actor (actor_name) values ('Orelle Baudrey');

insert into film (film_title) values ('Kissing Jessica Stein');
insert into film (film_title) values ('Tatort: Im Schmerz geboren');
insert into film (film_title) values ('Camille');
insert into film (film_title) values ('Tracey Fragments, The');
insert into film (film_title) values ('Magic of Belle Isle, The');
insert into film (film_title) values ('Legend of Boggy Creek, The');
insert into film (film_title) values ('Ketchup Effect, The (Hip Hip Hora!)');
insert into film (film_title) values ('Mystery of the Third Planet, The (Tayna tretey planety)');
insert into film (film_title) values ('Colin Quinn: Long Story Short');
insert into film (film_title) values ('Lady and the Reaper, The (Dama y la muerte, La)');
insert into film (film_title) values ('Whole Town''s Talking, The (Passport to Fame)');
insert into film (film_title) values ('Entre ses mains');
insert into film (film_title) values ('High Hopes');
insert into film (film_title) values ('Zincirbozan');
insert into film (film_title) values ('Intruders');
insert into film (film_title) values ('Cold Souls');
insert into film (film_title) values ('Dogs');
insert into film (film_title) values ('Dry Summer (Susuz yaz) (Reflections)');
insert into film (film_title) values ('Shining, The');
insert into film (film_title) values ('180° South (180 Degrees South) (180° South: Conquerors of the Useless)');
insert into film (film_title) values ('Latitudes');
insert into film (film_title) values ('Jack''s Back ');
insert into film (film_title) values ('Grapes of Death, The (Raisins de la mort, Les)');
insert into film (film_title) values ('Toy Story 2');
insert into film (film_title) values ('In a Lonely Place');
insert into film (film_title) values ('Quarantine 2: Terminal');
insert into film (film_title) values ('Leonard Part 6');
insert into film (film_title) values ('Música Campesina (Country Music)');
insert into film (film_title) values ('Bruno (Dress Code, The)');
insert into film (film_title) values ('Charlie Countryman');
insert into film (film_title) values ('Escape from New York');
insert into film (film_title) values ('How I Killed My Father (a.k.a. My Father and I) (Comment j''ai tué mon Père)');
insert into film (film_title) values ('Prince of Persia: The Sands of Time');
insert into film (film_title) values ('Wave, The (Welle, Die)');
insert into film (film_title) values ('Atragon (Kaitei Gunkan)');
insert into film (film_title) values ('Farewell to Arms, A');
insert into film (film_title) values ('The Dark Horse');
insert into film (film_title) values ('Tristana');
insert into film (film_title) values ('Love the Beast');
insert into film (film_title) values ('Deadbolt');
insert into film (film_title) values ('Chicago Massacre: Richard Speck');
insert into film (film_title) values ('Mistress');
insert into film (film_title) values ('Fan, The');
insert into film (film_title) values ('Investigation of a Citizen Above Suspicion (Indagine su un cittadino al di sopra di ogni sospetto)');
insert into film (film_title) values ('Rich and Famous (Gong woo ching)');
insert into film (film_title) values ('Blackthorn');
insert into film (film_title) values ('Ladybug Ladybug ');
insert into film (film_title) values ('Jonah: A VeggieTales Movie');
insert into film (film_title) values ('Flirting');
insert into film (film_title) values ('Armour of God II: Operation Condor (Operation Condor) (Fei ying gai wak)');
insert into film (film_title) values ('Crow, The: Wicked Prayer');
insert into film (film_title) values ('Crash Reel, The');
insert into film (film_title) values ('Governess, The');
insert into film (film_title) values ('Predator 2');
insert into film (film_title) values ('Bride of Re-Animator');
insert into film (film_title) values ('The Year Without a Santa Claus');
insert into film (film_title) values ('Friends of God: A Road Trip with Alexandra Pelosi');
insert into film (film_title) values ('Tracers');
insert into film (film_title) values ('Colony, The');
insert into film (film_title) values ('What Have You Done to Solange?');
insert into film (film_title) values ('La cravate');
insert into film (film_title) values ('White Fang (Zanna Bianca)');
insert into film (film_title) values ('Blue Gold: World Water Wars');
insert into film (film_title) values ('Weirdsville');
insert into film (film_title) values ('Half Past Dead');
insert into film (film_title) values ('Secret of Santa Vittoria, The');
insert into film (film_title) values ('Family Tree, The');
insert into film (film_title) values ('Operation Crossbow');
insert into film (film_title) values ('Skippy');
insert into film (film_title) values ('Standing in the Shadows of Motown');
insert into film (film_title) values ('True Legend (Su Qi-Er)');
insert into film (film_title) values ('Cuckoo, The (Kukushka)');
insert into film (film_title) values ('Deliver Us from Eva');
insert into film (film_title) values ('Vampyr');
insert into film (film_title) values ('Fever');
insert into film (film_title) values ('Candyman 3: Day of the Dead');
insert into film (film_title) values ('Day of the Locust, The');
insert into film (film_title) values ('Being Flynn');
insert into film (film_title) values ('Max Payne');
insert into film (film_title) values ('Children of Dune');
insert into film (film_title) values ('Women on the 6th Floor, The (Les Femmes du 6ème Étage)');
insert into film (film_title) values ('Jolene');
insert into film (film_title) values ('Company of Heroes');
insert into film (film_title) values ('Austin Powers: The Spy Who Shagged Me');
insert into film (film_title) values ('Wer');
insert into film (film_title) values ('Topaz');
insert into film (film_title) values ('Tough and Deadly');
insert into film (film_title) values ('Westerner, The');
insert into film (film_title) values ('Upswing (Nousukausi)');
insert into film (film_title) values ('Hollywood or Bust');
insert into film (film_title) values ('Life is to Whistle (Vida es silbar, La)');
insert into film (film_title) values ('That''s Life!');
insert into film (film_title) values ('Other Side of Bollywood, The');
insert into film (film_title) values ('Graveyard of Honor Shin jingi no hakaba');
insert into film (film_title) values ('Funny About Love');
insert into film (film_title) values ('Doors, The');
insert into film (film_title) values ('Hiroshima');
insert into film (film_title) values ('Curious George');
insert into film (film_title) values ('Day of the Doctor, The');
insert into film (film_title) values ('Print the Legend');

