CREATE TABLE IF NOT EXISTS comment (
id  INTEGER PRIMARY KEY AUTOINCREMENT,
post_id  INTEGER NOT NULL,
comment VARCHAR(50) NOT NULL,
FOREIGN KEY (post_id) REFERENCES post(id)
);


CREATE TABLE IF NOT EXISTS post (
id  INTEGER PRIMARY KEY AUTOINCREMENT,
txt VARCHAR(50) NOT NULL
);


INSERT INTO post (txt) VALUES ("post1");
INSERT INTO post (txt) VALUES ("post2");
INSERT INTO post (txt) VALUES ("post3");
INSERT INTO post (txt) VALUES ("post4");
INSERT INTO post (txt) VALUES ("post5");
INSERT INTO post (txt) VALUES ("post10000000000000000000000");

